### ISSUE TITLE
AccessDenied error occurs when clicking on a File block

### ISSUE THREAD

**Issue by ndotcom** [linyows/rotion#55]
### Symptom
When clicking on a File block in the demo of the rotion project, the following AccessDenied error occurs:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  <X-Amz-Expires>3600</X-Amz-Expires>
  <Expires>2024-04-12T14:38:16Z</Expires>
  <ServerTime>2024-04-15T00:57:25Z</ServerTime>
  <RequestId>Z44SGQX4W0Z4MN8B</RequestId>
  <HostId>XJL+6lVm7ySEZHrhxxbcxh0xSv7pm5uFJvmpAYNPq+9sUtmZfQuASZOR57gywRDKd7tO5fHIw3u50L/iLRRidQ==</HostId>
</Error>
```

### Steps to reproduce
1. [Access the demo page of the rotion project](https://rotion.linyo.ws/block)
2. Click on a File block

Please investigate and fix the error related to the File block. Let me know if you need more information or have any additional questions. Thank you.

**Comment by linyows** [comment]
Thank you for the report. It seems to be a 403 error because you have direct access to the content of Notion. Also, not only the File block but also the PDF block was the same. We will respond soon.
